added profile page #73
infiniteoverflow/Libro pull request #88
Opened 2021-03-22 16:52 UTC by amanxnanda

### Related Issue
- Fixes #73

### Proposed Changes
- Change 1
- Added Profile page in the lib folder
- Change 2
- Added font_awesome_flutter package for icons

### Checklist
- [x] Tested
- [x] No Conflicts
- [x] Change In Code
- [ ] Change In Documentation

### Screenshots (Optional)
<img src = "https://user-images.githubusercontent.com/34944818/111962330-31729180-8b18-11eb-81f5-9e0c5318ec55.png" height = "500">

2021-03-22 17:11 UTC, Souvikns requested changes
Firstly, you have a color constant, re-allocate that to the `utils/constants.dart`, then import it from there.

2021-03-22 17:45 UTC, amanxnanda commented
@Souvikns I thought so, for some reason I was getting an error while import. Anyway I'll try

2021-03-23 03:33 UTC, infiniteoverflow approved these changes

2021-03-23 03:36 UTC, infiniteoverflow commented
@amanxnanda Work on the changes requested by Souvik , rest all looks good

2021-03-24 02:15 UTC, infiniteoverflow requested changes

2021-03-24 02:15 UTC, infiniteoverflow commented on pubspec.yaml
>    google_fonts: ^2.0.0
google_fonts has been repeated in the pubspec.yaml file. Kindly remove this line.

2021-03-26 20:14 UTC, Souvikns commented
@amanxnanda are you still working on this PR.

2021-04-04 04:11 UTC, infiniteoverflow commented
@amanxnanda Are you still working on this PR ? There are some changes to make , can you look into it. If you are not able to , then we may have to assign someone else for the same.

2021-04-13 07:27 UTC, closed without merging